title: Project

fields:
  title:
    label: Title
    type: text
  teaser:
    label: Teaser
    type: textarea
  date:
    label: Date
    type: date
  blocks:
    label: Description
    type: blocks
  relatedQuestions:
    label: Related Research Questions
    type: pages
    query: site.find('research-questions').children
  type:
    label: Type
    type: select
    options:
      concept: Concept
      prototype: Prototype
      experiment: Experiment
      thought-experiment: Thought Experiment
  icon:
    label: Icon
    type: files
    max: 1
    layout: cards
