title: Project

fields:
  title:
    label: Title
    type: text
  date:
    label: Date
    type: date
  blocks:
    label: Description
    type: blocks
  relatedQuestions:
    label: Related Research Questions
    type: pages
    query: site.find('research-questions').children
  type:
    label: Type
    type: select
    options:
      realistic: Realistic
      crazy: Crazy
      weird: Weird
      futuristic: Futuristic